travis:
  secure:
    BINSTAR_TOKEN: KtC5Ed6l7/X1LO/zrYpOSU/+f7d24r/wXSmhEtLw/BbMPuxx/YHOiDAdbTR63KYHqSTzWtZEjCYjXK966H1j0SmPL6E/oqDDIPAutibN8M59Z7/LtEj0zMrT4NBLrMmw1DTDj4J6iRvSCy3d+Ig32E2zmU6UF++juf+MGDYJ7CjIXw9rDF6S7ur6qwbqosK5C3wWQMP5g6KYSS3/SvNAZIsWTsmczBiLe2LVhAxO/K1fTjK9BSEw6cduKAOfUuVi9Iy5kRONWUXYonED1m5BIOxoocfUlUCTD9+m1FqFCSpSQGPc1wVhdYbFUog7mG1DsX1Nr+Z7Ud7aHyNNscFZWMmlJQSBNliz3fRjcA2vP9BdfJMkBUntS0nqrReeLlpYhcbsSv1SbcmAaR/u9JVciGkxL4YxEZ3HOpuCEqqKPavyg8Iqj7DyfolYvPkXGmNTC+0nAqnWEqCRFlCn2mZE7IScn1tmUGLfae5rKpvQLvbzkwGlLd0WcG9UMvlT+axQUlRPbNYmzNDGmPiyQEl7u659OlMIMZPwJjcXxXSXGHbXRuJ2h6hojS5YtqVfUQfbtHiqq5T6a05soN6IvaMrQ3LeDttldx5pcnPsPvnjTDs6QZCwVErHmbDTOY5KmIcINkBYid4mul2bBeMDK5HIK7Rh2RYnn2fcCMOi2/x7wt8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
