travis:
  secure:
    BINSTAR_TOKEN: LnSQ+JpzaQBW0vrQXcBBSY3wECyEMl2R5vMZgbc0pXYRB6Ngg2Kz9DCXHQhZYjd2ypQAmvS2+S7VmTD4U7KTdooQOOuR+uHutCQ0UHHLlR4+cJ25ItyT7Hl3viPun9FxAW6zCFF8oI2CAUSPhy3lvuQK7j9Yat/2pVIsGY/gctpwZGKX4TV0AAhSZjkCQpd8FRntmKiv2DIMDBWYPvnB0cXF/472iyWkf5P3PYXjtwQPM9ZGMiiWy8Zn8GevHRQjbCjTUt4IhoOysCQaVH7wIlSNQLxu31a6QFK/3kbW+AzWCJl3nAWRLkgWKc8308MIFFMjds5LFwkUF1qMEktcPG+miwu012ii+4vLIYlMGC/LmvoK+cSz2cUKQIiU0kx3F3LFCjScHGPuKYRABs7yvVpBwQT1QUOT0TVc5l3vw/hxdhzlOLJoB6tvNtQqPkjWmFzSA3+BjoCYhMpsInB8uy86S2AAdIbN21CGafobxA05XxFGiuCnvef7UL+5r8OD4PZqb85TS1yw8rdBCYj4daXh07xePV+4Hf3DL7E/474MZ1knce5js5fNJDN2Nl/jN+42Y/8+pVlb7nPaqqZ9QkrOrFnP8fvyOger4hMI9qKUo+tpN0c7P24+T8hKnskA/r2iaikGSiply5hyNXviZfWfzoG8/ZDgBwxX+p0SGy0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
