travis:
  secure:
    BINSTAR_TOKEN: mcBZD7kwCahCvAlkxCh3tyPsplUSIml5E9rt1wtcOFdemp6KcNNWesGUDpXeeZ/RFVZb0StBHiofkQm2mjw9IBBAMnEa3hmSaebkRVeg+r4jYVmB1Z0G2UY0QsNAkPzNfcbJ/hH4NpoSIfOXtqwPCq8US6aqqY2ITk3heuHUUfF+TbTPggJZG4bsc90NlKPKzFdCirLusZ6AMh0Ex9zMnCENHLLLCG2NukRJmY7K/7sFMeDEA+PV8EzlXmjHxghgBv7y4BTyDubCBd5AC44qqML2v21Iiii9Fc3S2hjjLBY8t9T08r4L8jqHDz/4N+Eg6idr268WqKAVPzo/yFIIqi0arxKPdy4tPdq7/K2Pm6py8FrW+/ubojAkYpbNe5057lo3OQRoXzXF5XZ9qYDCwoIn6VtbqoATC4CwNUWv7nXxCvjF+hybgUuaYIHJaPGkuhlOM91zudjY6Jojn+4YKSty3H+K6pocZ4Kp45IvThfufzmz4wyNyr8xRdRfjPHxvlJ1dUtl0Ra/2BonsXg1k1+19UoCx/D8TNzK2b6FTetubmvXt9FNYNmsMkkDC4NxHLiU7KWl0Z/6BxXZB9bNHlbM+2UQGiYoy0w8CD/fyvEjq85Q5fqXvuxmmEZ65/LYU8nZEbtRWEO7ErEjhU7FGtDRdFtW4Fzsmr7zwHuM2kg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
