travis:
  secure:
    BINSTAR_TOKEN: R3lrWgSS4ue4de2yaOaHoigi32hzWRdOJwfyMp66KZRdqnii9MPm8GOExJwQ6jhBWwzdpqkqWqHJAo7N1WhtBJjLfyvkUBLWt+jZjyRCIgAxUhbVBPPOvBNEx1bIPOOk214sYvXIRHK5V0uHztWXMbleQFxVzqHvRUdEkvRSyWfBJwXSLgf8G2CyIEUTtWFljvCqjDeHcAGNv1erHbMHhxAQW4CZpw6DJDd2qtK3lxi0y1oojzj9RJ4v5sxqLoDn3MK//nUBJEJOxJbOI3SreulkLY3oco5kDxD/gwTSDsNr5CvKwT44y8jxW0R8EiwQVg9prSI1rSvEItGBJ2SN7quCPV99qP6BBjDnXurHp5nMC75ezIwZa5wRCWG9l+OUSDi/swRDov1Y/DK6j3uRSEIQuymBu0jYoFcpPFGUDayp2iUE2W/NvlYEHOXqM5bVRjM7hlXEygdmegX5eK4gIehe0e+v6ryv6a/ew0kzalfeUgukrLzZF0AqQRM3W8m0JtkwNUBVFcSNjNML2n8TMAzxGzdmPzHC4IACCxC5UZlLmUAoeo18aqPgX0RDUfS4Wk441tBroiJNDxk+PovhGNRzW5fRKZhY4UL4EgQWNVRcHipGkTXqx+CNXroySD1bNhyjhXH6ye/MgC15ucGTREImxilRJYoNwruPMTCgBgY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
