travis:
  secure:
    BINSTAR_TOKEN: TsseUAhHaVaqfi6tmd8DtKGDgXlAJrjME40JL1BuUjkmvbCuz0sRXQsK2PpiVJTbaz2W76aF8gE4joCQbMG6DmpDCf1b2dlzf5eSqgQ5xgw1XEiKJrZ6gMgUAzkxCDZpFY7WrUDyX5Atv9+pOY0rNbHmg1mjU93LS/d4gjHqhDltBe4rVuOD3Qj5/5S3sz6TIh6NZKpAc8OePWub5IP8hSzGplAoz6CEOJWs+YDcGOcukOg+eGNWGTujAVU7dBR+hwH0QtlYuRagcR1NXYqfLQFPOO+qVMasHDeUOfxOPFfOqHDPQCd/c12miu2xwjrw8uPTjczx+iy59OhynnVdfaO8PE2tzNZRCdALkzFcT6sFVPytvrxRP6MXl0TSwQY0pmQfi76V9CRv3jXHloRPgnvlWmvNW3rj15kvfSXYgqLAOvoo6rOUDEejv+BRZQ6zviUtb3VzvCeRvrHzwAlsyhfaLmpk2w49XBOjo+/vJvXUK8cJS8ZhIXx/IbEIAdhsbHTc4HxSHBtfvTJF2C1ns5YrgsERldqY3WEynXXMaKxvkxs6mL9suhN1vMMmW4ln3gGFxMyGh1I/fL2MwsmPXJs78LOSflFrIjMRM6W9FJeR4/sW/SYZxvkVxU8k8dYiubr/3WN5xA/EwBsHkBEEZYNA8ndGKWkohhjCqX9NbSI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
