travis:
  secure:
    BINSTAR_TOKEN: kXzliV1X2uo8plaeow4NaRpUqog5P8SgWTDUW4cKly5/CrHXe1ctekYzu2HyTSye7PZQdPuaJEg5+kCISvwMH46qsJipyEVOjZIGTzPSWBEOBvtm7FVnoQV3hH7nFkRVik4pe+u3KcGYYV3lVnBzPKk+xLr+cAsJ4YxGILEcXiog6FPUrtBKLiYvWjrs15KwZXdOEA7Lew5lQfU4wQfqg5OltzTy9sw2cFPN7aHU9+qoZwxPSPlaOmwyjE851hHetmTF+bZIdRm3h8dvDanKq3CTFHhXIByXu0nmGq9PFWKbQRnYYzbSBYNsJOjtqo8lA3OCjPsVzbu+scVOFIBI6EIHcUn2XukBg/2FmVclN9zKmbAb7MIyjwnXJjlu61IFJIT9AwFFLaDAXUq4mVxvo3iGT/KO/x2w0YvKEVNp2Bwd8rClfB2D58swa3JOy1XS912BYrmQryVrLMJIb+bEZVinPMF1KAk8hpseIbsXglXZJQexf8ucAO8SONeTW1hKx+vrSgc7qvO8IdPTBpt4Oe1UmceEpb/7T/dxFy4MA9VOyJ29ihmil5SrtCstKtGcWhyNbWhQJV2MW8RV/B9+fVlWyXG+qkRjzwAGlj4iP56UDg8AmfD1QuHnV2eDkOF17h/+U9ea0c18ZjEqQ1gREjCR6JIRTVXFi+AJ/6sN3gU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
